### ISSUE TITLE
More suported file formats.

### ISSUE THREAD

**Issue by RaphaelK12** [Didgy74/DTex#3]
Hello, I was developing a library that I believe has the same purpose as this, take a look at my repository, it has tga, pcx, pbm, jpg and png formats.

https://github.com/RaphaelK12/Imagem-View

For now I'm without a computer, so my project is stopped, I believe you can use some things in yours, all my code is free to the public.
I didn't want to stop my project, besides adding file formats, I'm also creating a class for storage and processing that is useful for image processing and easy to use, having as first focus, OpenGL, Vulkan and lastly DirectX.

I have a repository for processing, but everything is a real mess, I have a lot of old code and unused files, so far it still doesn't compile, it's just a draft of what will be an image storage and processing library.

https://github.com/RaphaelK12/ImagemEditorTRK

**Comment by aleokdev** [comment]
This isn't even an issue. This is just an advertisement.
